### PR TITLE
Feature/jar out

### PR DESCRIPTION
**Pull request by daviscook477**
Now adds option for the patched jar to be written out post patching for debugging purposes to be able to better see how everything broke every time Megacrit releases a weekly patch.

### CODE REVIEW

**Comment by kiooeht** [comment]
1. Please remove the Eclipse project files (`.classpath`, `.project`, `.settings/`) and add them to the `.gitignore`.
2. I doubt normal users will need this feature and modders probably won't need it often. The biggest use case will likely be keeping BaseMod working, so I think removing it from the UI and keeping it just as a command line flag and config file options would be best.

**Comment by daviscook477** [comment]
Sounds good. I'll ping you when that's done.

**Comment by daviscook477** [comment]
Changes done.

**Comment by daviscook477** [comment]
Seems like jd-gui has some problems decompiling some of the written `*.class` files but Luyten can decompile things just fine. Since looking at the patched jar doesn't need exact line numbers I think this is a fine compromise.

**Pull request merged**
